### ISSUE TITLE
deploy a Framework-dependent executable ⚙🐱‍🏍🚀

### ISSUE THREAD

**Issue by BryanWilhite** [BryanWilhite/Songhay.Publications#10]
https://docs.microsoft.com/en-us/dotnet/core/deploying/index#framework-dependent-executables-fde

https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-publish?tabs=netcore21

**Comment by BryanWilhite** [comment]
the Visual-Studio-centric approach: https://community.devexpress.com/blogs/wpf/archive/2019/11/11/how-to-deploy-a-net-core-3-app.aspx

**Comment by BryanWilhite** [comment]
[this command](https://github.com/dotnet/cli/issues/11439), `dotnet publish -c Release --self-contained false -r win-x64`, is the base of this `win-x64` task:
![image](https://user-images.githubusercontent.com/5226627/70361826-caa06a80-1837-11ea-9a40-38934dee511b.png)

produces this output:
![image](https://user-images.githubusercontent.com/5226627/70361858-ead02980-1837-11ea-9783-3e51b782c3eb.png)

**Comment by BryanWilhite** [comment]
for `linux-x64`:
![image](https://user-images.githubusercontent.com/5226627/70362863-3a642480-183b-11ea-9a7e-f795d7c9d9bd.png)
![image](https://user-images.githubusercontent.com/5226627/70362950-7e572980-183b-11ea-9bfe-6bc4044d400b.png)

**Comment by BryanWilhite** [comment]
the binary is working fine:

```console
me@ubuntu-vm:~/Songhay.Publications/Songhay.Publications.Shell/bin/Release/netcoreapp2.2/linux-x64/publish$ ./Songhay.Publications.Shell MarkdownEntryActivity --base-path /home/me/Songhay.Publications/Songhay.Publications.Shell.Tests/md-presentation-layout/shell --settings-file md-publish-entry.json --base-path-required
Songhay.Publications.Shell 1.0.2.0
The Studio Publications Shell for commandline automation of Activities.
(c) 2019 Bryan D. Wilhite

Activities Assembly:
Songhay.Publications.Activities 1.0.2.0
The Studio Publications Activities for commandline automation and cloud orchestraction.
(c) 2019 Bryan D. Wilhite
Loading configuration...
Building configuration...
```

[`./Songhay.Publications.Shell MarkdownEntryActivity --base-path /home/me/Songhay.Publications/Songhay.Publications.Shell.Tests/md-presentation-layout/shell --settings-file md-publish-entry.json --base-path-required` :eyes:  ]

but `appsettings.json` is not being deployed:

```console
Unhandled Exception: System.IO.FileNotFoundException: The configuration file './appsettings.json' was not found and is not optional. The physical path is '/home/me/Songhay.Publications/Songhay.Publications.Shell/bin/Release/netcoreapp2.2/linux-x64/publish/appsettings.json'.
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load(Boolean reload)
   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at Songhay.Publications.Shell.Program.Run(String[] args) in /home/me/Songhay.Publications/Songhay.Publications.Shell/Program.cs:line 26
   at Songhay.Publications.Shell.Program.Main(String[] args) in /home/me/Songhay.Publications/Songhay.Publications.Shell/Program.cs:line 47
Aborted (core dumped)
```
