### ISSUE TITLE
`System.Text.EncoderFallbackException` during `AddEntryExtract` command

### ISSUE THREAD

**Issue by BryanWilhite** [BryanWilhite/Songhay.Publications#13]
```console
Unhandled Exception: System.Text.EncoderFallbackException: Unable to translate Unicode character \\uD83D at index 964 to specified code page.
   at System.Text.EncoderExceptionFallbackBuffer.Fallback(Char charUnknown, Int32 index)
   at System.Text.EncoderFallbackBuffer.InternalFallback(Char ch, Char*& chars)
   at System.Text.UTF8Encoding.GetBytes(Char* chars, Int32 charCount, Byte* bytes, Int32 byteCount, EncoderNLS baseEncoder)
   at System.Text.EncoderNLS.GetBytes(Char[] chars, Int32 charIndex, Int32 charCount, Byte[] bytes, Int32 byteIndex, Boolean flush)   
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.IO.StreamWriter.Write(String value)
   at System.IO.File.WriteAllText(String path, String contents)
   at Songhay.Publications.Activities.MarkdownEntryActivity.AddEntryExtract(String entryPath) in ..\Songhay.Publications\Songhay.Publications\Activities\MarkdownEntryActivity.cs:line 41
   at Songhay.Publications.Activities.MarkdownEntryActivity.Start(ProgramArgs args) in ..\Songhay.Publications\Songhay.Publications\Activities\MarkdownEntryActivity.cs:line 157
   at Songhay.Extensions.IActivityExtensions.StartActivity(IActivity activity, ProgramArgs args, TraceSource traceSource)
   at Songhay.Publications.Shell.Program.Main(String[] args) in ..\Songhay.Publications\Songhay.Publications.Shell\Program.cs:line 45
The terminal process terminated with exit code: 1
```

**Comment by BryanWilhite** [comment]
tonight i assume that this is writing UTF-16: `File.WriteAllText(entryInfo.FullName, $"{finalEdit}");`

will verify later 👀

**Comment by BryanWilhite** [comment]
`\\uD83D` seems related to https://charbase.com/1f602-unicode-face-with-tears-of-joy
![image](https://user-images.githubusercontent.com/5226627/71539367-1b175f00-28f0-11ea-8cdb-f1b12e67dd13.png)

**Comment by BryanWilhite** [comment]
further investigations shows this:

![image](https://user-images.githubusercontent.com/5226627/71960763-a9ba9480-31aa-11ea-91b7-4374a01d2e98.png)

tucked under this:

![image](https://user-images.githubusercontent.com/5226627/71960793-be972800-31aa-11ea-9cd7-97e1ad4f0019.png)

**Comment by BryanWilhite** [comment]
the problem char is also hidden on Linux:
![image](https://user-images.githubusercontent.com/5226627/72034206-37e55800-3249-11ea-81db-0c3b5ac4ff1f.png)

**Comment by BryanWilhite** [comment]
i'm pretty sure @brandonroberts is not going to know why his tweet had all of these unsupported characters in them 🤷‍♂ 

i set up a little test, `ShouldRemoveUnsupportedCharacters`, to remove `\\uD83D` but this led to other `\\uD*` chars:
![image](https://user-images.githubusercontent.com/5226627/72040316-05ddf100-325d-11ea-8e62-66d87f23d887.png)
```console
`\uD83D` found 11 times.
`\uDC68` found 2 times.
`\uDCBB` found 2 times.
`\uDC40` found 2 times.
`\uDCE2` found 2 times.
`\uDD25` found 1 times.
`\uDE2C` found 1 times.
`\uDE07` found 1 times.
```

![image](https://user-images.githubusercontent.com/5226627/72040398-4a698c80-325d-11ea-8602-2c8c51e87bbe.png)

**Comment by BryanWilhite** [comment]
because i am a total weirdo, i manually replaced the emojis breaking Windows codepages with Windows equivalents:
![image](https://user-images.githubusercontent.com/5226627/72040828-9e28a580-325e-11ea-9442-ef3465720812.png)

Windows glyphs | screenshot
-- | --
✍🏿👀📢 | ![image](https://user-images.githubusercontent.com/5226627/72040884-cfa17100-325e-11ea-83f0-0c004fbb569f.png)
👨🏿‍💻✍🏿🏀 | ![image](https://user-images.githubusercontent.com/5226627/72040918-e647c800-325e-11ea-9f83-0f39b90fdaec.png)

**Comment by BryanWilhite** [comment]
this test is showing me that the emojis written to a fresh UTF-8 file behave as expected:
![image](https://user-images.githubusercontent.com/5226627/72042320-08dbe000-3263-11ea-80d3-239c70145f12.png)

**Comment by BryanWilhite** [comment]
i have not seen this exception in quite a while: it is just possible that this Markdig issue addressed it: https://github.com/xoofx/markdig/issues/72
