### ISSUE TITLE
`Unhandled Exception: Newtonsoft.Json.JsonReaderException` but current Markdown file is not specified

### ISSUE THREAD

**Issue by BryanWilhite** [BryanWilhite/Songhay.Publications#18]
Executing task: `Songhay.Publications.Shell IndexActivity`:

```console
Songhay.Publications.Shell 1.0.14.0
The Studio Publications Shell for commandline automation of Activities.
(c) 2020 Bryan D. Wilhite

Activities Assembly:
Songhay.Publications 1.0.15.0
Core reusable definitions for Songhay Studio Publications
(c) 2020 Bryan D. Wilhite
Loading configuration...
Building configuration...

Unhandled Exception: Newtonsoft.Json.JsonReaderException: Unexpected end of content while loading JObject. Path 'clientId', line 14, position 73.
   at Newtonsoft.Json.Linq.JContainer.ReadTokenFrom(JsonReader reader, JsonLoadSettings options)
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
   at Songhay.Publications.Extensions.MarkdownEntryExtensions.ToMarkdownEntry(FileInfo entry) 
```

**Comment by BryanWilhite** [comment]
this change in `.ToMarkdownEntry()` is a direct response:

```csharp
JObject frontMatter = null;
try
{
    frontMatter = JObject.Parse(json);
}
catch (JsonReaderException ex)
{
    traceSource?.TraceError(ex);
}
```
